<?php

/**
 * BasemdNewsLetterGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $mdNewsLetterGroupUser
 * @property Doctrine_Collection $mdNewsLetterGroupSended
 * @property Doctrine_Collection $actividades
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method string              getName()                    Returns the current record's "name" value
 * @method Doctrine_Collection getMdNewsLetterGroupUser()   Returns the current record's "mdNewsLetterGroupUser" collection
 * @method Doctrine_Collection getMdNewsLetterGroupSended() Returns the current record's "mdNewsLetterGroupSended" collection
 * @method Doctrine_Collection getActividades()             Returns the current record's "actividades" collection
 * @method mdNewsLetterGroup   setId()                      Sets the current record's "id" value
 * @method mdNewsLetterGroup   setName()                    Sets the current record's "name" value
 * @method mdNewsLetterGroup   setMdNewsLetterGroupUser()   Sets the current record's "mdNewsLetterGroupUser" collection
 * @method mdNewsLetterGroup   setMdNewsLetterGroupSended() Sets the current record's "mdNewsLetterGroupSended" collection
 * @method mdNewsLetterGroup   setActividades()             Sets the current record's "actividades" collection
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdNewsLetterGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_news_letter_group');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 256, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 256,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mdNewsLetterGroupUser', array(
             'local' => 'id',
             'foreign' => 'md_newsletter_group_id'));

        $this->hasMany('mdNewsLetterGroupSended', array(
             'local' => 'id',
             'foreign' => 'md_newsletter_group_id'));

        $this->hasMany('actividades', array(
             'local' => 'id',
             'foreign' => 'md_news_letter_group_id'));
    }
}