<?php

/**
 * Baseemails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $from_name
 * @property string $from_mail
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getType()      Returns the current record's "type" value
 * @method string  getFromName()  Returns the current record's "from_name" value
 * @method string  getFromMail()  Returns the current record's "from_mail" value
 * @method emails  setId()        Sets the current record's "id" value
 * @method emails  setType()      Sets the current record's "type" value
 * @method emails  setFromName()  Sets the current record's "from_name" value
 * @method emails  setFromMail()  Sets the current record's "from_mail" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseemails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emails');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('from_name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('from_mail', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));


        $this->index('type_index', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}