<?php

/**
 * Basebilletera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $credito
 * @property integer $deuda
 * @property integer $impuesto
 * @property usuario $usuario
 * 
 * @method integer   getId()       Returns the current record's "id" value
 * @method integer   getCredito()  Returns the current record's "credito" value
 * @method integer   getDeuda()    Returns the current record's "deuda" value
 * @method integer   getImpuesto() Returns the current record's "impuesto" value
 * @method usuario   getUsuario()  Returns the current record's "usuario" value
 * @method billetera setId()       Sets the current record's "id" value
 * @method billetera setCredito()  Sets the current record's "credito" value
 * @method billetera setDeuda()    Sets the current record's "deuda" value
 * @method billetera setImpuesto() Sets the current record's "impuesto" value
 * @method billetera setUsuario()  Sets the current record's "usuario" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basebilletera extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('billetera');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('credito', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('deuda', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('impuesto', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'id',
             'foreign' => 'billetera_id'));
    }
}