<?php

/**
 * Baseusuario_actividades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $actividad_id
 * @property usuario $usuario
 * @property actividades $actividad
 * 
 * @method integer             getUsuarioId()    Returns the current record's "usuario_id" value
 * @method integer             getActividadId()  Returns the current record's "actividad_id" value
 * @method usuario             getUsuario()      Returns the current record's "usuario" value
 * @method actividades         getActividad()    Returns the current record's "actividad" value
 * @method usuario_actividades setUsuarioId()    Sets the current record's "usuario_id" value
 * @method usuario_actividades setActividadId()  Sets the current record's "actividad_id" value
 * @method usuario_actividades setUsuario()      Sets the current record's "usuario" value
 * @method usuario_actividades setActividad()    Sets the current record's "actividad" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseusuario_actividades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_actividades');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('actividad_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('actividades as actividad', array(
             'local' => 'actividad_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}