<?php

/**
 * Basecuenta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $cobro
 * @property Doctrine_Collection $cuentapadre
 * @property Doctrine_Collection $cuentausuario
 * @property Doctrine_Collection $factura
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method Doctrine_Collection getCobro()         Returns the current record's "cobro" collection
 * @method Doctrine_Collection getCuentapadre()   Returns the current record's "cuentapadre" collection
 * @method Doctrine_Collection getCuentausuario() Returns the current record's "cuentausuario" collection
 * @method Doctrine_Collection getFactura()       Returns the current record's "factura" collection
 * @method cuenta              setId()            Sets the current record's "id" value
 * @method cuenta              setNombre()        Sets the current record's "nombre" value
 * @method cuenta              setCobro()         Sets the current record's "cobro" collection
 * @method cuenta              setCuentapadre()   Sets the current record's "cuentapadre" collection
 * @method cuenta              setCuentausuario() Sets the current record's "cuentausuario" collection
 * @method cuenta              setFactura()       Sets the current record's "factura" collection
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecuenta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuenta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('cobro', array(
             'local' => 'id',
             'foreign' => 'cuenta_id'));

        $this->hasMany('cuentapadre', array(
             'local' => 'id',
             'foreign' => 'cuenta_id'));

        $this->hasMany('cuentausuario', array(
             'local' => 'id',
             'foreign' => 'cuenta_id'));

        $this->hasMany('factura', array(
             'local' => 'id',
             'foreign' => 'cuenta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}