<?php

/**
 * Baseactividades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property float $costo
 * @property enum $horario
 * @property integer $md_news_letter_group_id
 * @property Doctrine_Collection $usuarios
 * @property mdNewsLetterGroup $mdNewsLetterGroup
 * @property Doctrine_Collection $usuario_actividades
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method string              getNombre()                  Returns the current record's "nombre" value
 * @method float               getCosto()                   Returns the current record's "costo" value
 * @method enum                getHorario()                 Returns the current record's "horario" value
 * @method integer             getMdNewsLetterGroupId()     Returns the current record's "md_news_letter_group_id" value
 * @method Doctrine_Collection getUsuarios()                Returns the current record's "usuarios" collection
 * @method mdNewsLetterGroup   getMdNewsLetterGroup()       Returns the current record's "mdNewsLetterGroup" value
 * @method Doctrine_Collection getUsuarioActividades()      Returns the current record's "usuario_actividades" collection
 * @method actividades         setId()                      Sets the current record's "id" value
 * @method actividades         setNombre()                  Sets the current record's "nombre" value
 * @method actividades         setCosto()                   Sets the current record's "costo" value
 * @method actividades         setHorario()                 Sets the current record's "horario" value
 * @method actividades         setMdNewsLetterGroupId()     Sets the current record's "md_news_letter_group_id" value
 * @method actividades         setUsuarios()                Sets the current record's "usuarios" collection
 * @method actividades         setMdNewsLetterGroup()       Sets the current record's "mdNewsLetterGroup" value
 * @method actividades         setUsuarioActividades()      Sets the current record's "usuario_actividades" collection
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseactividades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actividades');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('costo', 'float', 10, array(
             'type' => 'float',
             'notnull' => true,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('horario', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'mañana',
              1 => 'tarde',
              2 => 'mañana y tarde',
             ),
             ));
        $this->hasColumn('md_news_letter_group_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('usuario as usuarios', array(
             'refClass' => 'usuario_actividades',
             'local' => 'actividad_id',
             'foreign' => 'usuario_id'));

        $this->hasOne('mdNewsLetterGroup', array(
             'local' => 'md_news_letter_group_id',
             'foreign' => 'id'));

        $this->hasMany('usuario_actividades', array(
             'local' => 'id',
             'foreign' => 'actividad_id'));
    }
}