<?php

/**
 * BasemdBlockedUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $md_user_id
 * @property string $reason
 * @property mdUser $mdUser
 * 
 * @method integer        getMdUserId()   Returns the current record's "md_user_id" value
 * @method string         getReason()     Returns the current record's "reason" value
 * @method mdUser         getMdUser()     Returns the current record's "mdUser" value
 * @method mdBlockedUsers setMdUserId()   Sets the current record's "md_user_id" value
 * @method mdBlockedUsers setReason()     Sets the current record's "reason" value
 * @method mdBlockedUsers setMdUser()     Sets the current record's "mdUser" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdBlockedUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_blocked_users');
        $this->hasColumn('md_user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('reason', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdUser', array(
             'local' => 'md_user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}