<?php

/**
 * BasemdNewsLetterUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $md_user_id
 * @property mdUser $mdUser
 * @property Doctrine_Collection $mdNewsletterSend
 * @property Doctrine_Collection $mdNewsLetterGroupUser
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getMdUserId()              Returns the current record's "md_user_id" value
 * @method mdUser              getMdUser()                Returns the current record's "mdUser" value
 * @method Doctrine_Collection getMdNewsletterSend()      Returns the current record's "mdNewsletterSend" collection
 * @method Doctrine_Collection getMdNewsLetterGroupUser() Returns the current record's "mdNewsLetterGroupUser" collection
 * @method mdNewsLetterUser    setId()                    Sets the current record's "id" value
 * @method mdNewsLetterUser    setMdUserId()              Sets the current record's "md_user_id" value
 * @method mdNewsLetterUser    setMdUser()                Sets the current record's "mdUser" value
 * @method mdNewsLetterUser    setMdNewsletterSend()      Sets the current record's "mdNewsletterSend" collection
 * @method mdNewsLetterUser    setMdNewsLetterGroupUser() Sets the current record's "mdNewsLetterGroupUser" collection
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdNewsLetterUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_news_letter_user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdUser', array(
             'local' => 'md_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('mdNewsletterSend', array(
             'local' => 'id',
             'foreign' => 'md_news_letter_user_id'));

        $this->hasMany('mdNewsLetterGroupUser', array(
             'local' => 'id',
             'foreign' => 'md_newsletter_user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}