<?php

/**
 * cobro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class cobro extends Basecobro
{
  
  public function postSave($event) {
    $this->getCuenta()->setPago($this->getCuenta()->getPago() + $this->getMonto());
    $this->getCuenta()->save();
    facturaHandler::payFacturasOfAccount($this->getCuentaId(), $this->getMonto());
    parent::postSave($event);
  }
  
  public function getFormatedMonto()
  {
    return number_format($this->getMonto(), 0, ',', '.');
  }

}
