<?php

/**
 * costosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class costosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object costosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('costos');
    }
}