<?php

/**
 * facturaFinalDetalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class facturaFinalDetalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object facturaFinalDetalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('facturaFinalDetalle');
    }
}