<?php

/**
 * mdGaleriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGaleriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGaleriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGaleria');
    }
	  public function findAllOrderByPosition($limit = null) {
	    $q = $this->createQuery('g')->orderBy('g.position asc');
			if($limit != null)
				$q->limit($limit);
	    return $q->execute();
	  }
	
		public function findByGroups($groups){
			if(count($groups)>0){
				$q = $this->createQuery('g');
				foreach($groups as $group){
					$q->orWhere(sprintf('g.curso_%s = true', $group));
				}
				return $q->orderBy('g.position asc')->execute();
			}else{
				return array();
			}
		}

		public function findByGroup($group){
			
			$q = $this->createQuery('g');
			$q->Where(sprintf('g.curso_%s = true', $group));
			return $q->orderBy('g.position asc')->execute();
		
		}

}