<?php

/**
 * Baseusuario_progenitor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $progenitor_id
 * @property usuario $usuario
 * @property progenitor $progenitor
 * 
 * @method integer            getUsuarioId()     Returns the current record's "usuario_id" value
 * @method integer            getProgenitorId()  Returns the current record's "progenitor_id" value
 * @method usuario            getUsuario()       Returns the current record's "usuario" value
 * @method progenitor         getProgenitor()    Returns the current record's "progenitor" value
 * @method usuario_progenitor setUsuarioId()     Sets the current record's "usuario_id" value
 * @method usuario_progenitor setProgenitorId()  Sets the current record's "progenitor_id" value
 * @method usuario_progenitor setUsuario()       Sets the current record's "usuario" value
 * @method usuario_progenitor setProgenitor()    Sets the current record's "progenitor" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseusuario_progenitor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_progenitor');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('progenitor_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('progenitor', array(
             'local' => 'progenitor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}