<?php

/**
 * Basecobro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cuenta_id
 * @property date $fecha
 * @property float $monto
 * @property cuenta $cuenta
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getCuentaId()  Returns the current record's "cuenta_id" value
 * @method date    getFecha()     Returns the current record's "fecha" value
 * @method float   getMonto()     Returns the current record's "monto" value
 * @method cuenta  getCuenta()    Returns the current record's "cuenta" value
 * @method cobro   setId()        Sets the current record's "id" value
 * @method cobro   setCuentaId()  Sets the current record's "cuenta_id" value
 * @method cobro   setFecha()     Sets the current record's "fecha" value
 * @method cobro   setMonto()     Sets the current record's "monto" value
 * @method cobro   setCuenta()    Sets the current record's "cuenta" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecobro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cobro');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cuenta_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('monto', 'float', 12, array(
             'type' => 'float',
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('cuenta', array(
             'local' => 'cuenta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}