<?php

/**
 * Basecuentausuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cuenta_id
 * @property integer $usuario_id
 * @property cuenta $cuenta
 * @property usuario $usuario
 * 
 * @method integer       getCuentaId()   Returns the current record's "cuenta_id" value
 * @method integer       getUsuarioId()  Returns the current record's "usuario_id" value
 * @method cuenta        getCuenta()     Returns the current record's "cuenta" value
 * @method usuario       getUsuario()    Returns the current record's "usuario" value
 * @method cuentausuario setCuentaId()   Sets the current record's "cuenta_id" value
 * @method cuentausuario setUsuarioId()  Sets the current record's "usuario_id" value
 * @method cuentausuario setCuenta()     Sets the current record's "cuenta" value
 * @method cuentausuario setUsuario()    Sets the current record's "usuario" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecuentausuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuentausuario');
        $this->hasColumn('cuenta_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('cuenta', array(
             'local' => 'cuenta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}