<?php

/**
 * Basedescuentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cantidad_de_hermanos
 * @property integer $porcentaje
 * 
 * @method integer    getId()                   Returns the current record's "id" value
 * @method integer    getCantidadDeHermanos()   Returns the current record's "cantidad_de_hermanos" value
 * @method integer    getPorcentaje()           Returns the current record's "porcentaje" value
 * @method descuentos setId()                   Sets the current record's "id" value
 * @method descuentos setCantidadDeHermanos()   Sets the current record's "cantidad_de_hermanos" value
 * @method descuentos setPorcentaje()           Sets the current record's "porcentaje" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basedescuentos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('descuentos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cantidad_de_hermanos', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('porcentaje', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}