<?php

/**
 * Basepagos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property integer $price
 * @property enum $mes
 * @property timestamp $fecha
 * @property boolean $out_of_date
 * @property usuario $usuario
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getUsuarioId()   Returns the current record's "usuario_id" value
 * @method integer   getPrice()       Returns the current record's "price" value
 * @method enum      getMes()         Returns the current record's "mes" value
 * @method timestamp getFecha()       Returns the current record's "fecha" value
 * @method boolean   getOutOfDate()   Returns the current record's "out_of_date" value
 * @method usuario   getUsuario()     Returns the current record's "usuario" value
 * @method pagos     setId()          Sets the current record's "id" value
 * @method pagos     setUsuarioId()   Sets the current record's "usuario_id" value
 * @method pagos     setPrice()       Sets the current record's "price" value
 * @method pagos     setMes()         Sets the current record's "mes" value
 * @method pagos     setFecha()       Sets the current record's "fecha" value
 * @method pagos     setOutOfDate()   Sets the current record's "out_of_date" value
 * @method pagos     setUsuario()     Sets the current record's "usuario" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepagos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pagos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mes', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 1,
              1 => 2,
              2 => 3,
              3 => 4,
              4 => 5,
              5 => 6,
              6 => 7,
              7 => 8,
              8 => 9,
              9 => 10,
              10 => 11,
              11 => 12,
             ),
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('out_of_date', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}