<?php

/**
 * costos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class costos extends Basecostos
{
  private static $costos = null;
  
  public static function getCosto($which = 'matutino')
  {
    if(is_null($which) || $which == "") $which = 'matutino';
    
    if(is_null(self::$costos))
    {
      $costos = Doctrine::getTable('costos')->findAll(Doctrine_Core::HYDRATE_ARRAY);
      if(count($costos) > 0)
      {
        self::$costos = $costos[0];
      }      
    }

    if(array_key_exists($which, self::$costos))
    {
      return number_format(self::$costos[$which], 2, '.', '');
    }
    else
    {
      throw new Exception('Debes ingresar los costos al sistema');
    }
  }
  
  public static function getSymbol()
  {
    return '$U';
  }
}
