<?php

/**
 * facturaUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class facturaUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object facturaUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('facturaUsuario');
    }
    
    public function retrieveByUserMonthAndYear($userId, $month, $year)
    {
        $query = $this->createQuery('f')
                ->addWhere('f.usuario_id = ?', $userId)
                ->addWhere('f.month = ?', $month)
                ->addWhere('f.year = ?', $year);
        return $query->fetchOne();
    }
}