<?php

/**
 * facturaFinal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class facturaFinal extends BasefacturaFinal
{
  public function getFormatedTotal()
  {
    return number_format($this->getTotal(), 0, ',', '.');
  }
  
  public function getFormatedPagadoDelTotal()
  {
    return number_format($this->getPagadodeltotal(), 0, ',', '.');
  }
  
  public function preDelete($event) {
	$cuenta = $this->getCuenta();
	$cuenta->setDebe($cuenta->getDebe() - $this->getTotal());
	parent::preDelete($event);
  }

}
