<?php

/**
 * usuario_progenitorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class usuario_progenitorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object usuario_progenitorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('usuario_progenitor');
    }
}