<?php

/**
 * cuentausuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cuentausuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object cuentausuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cuentausuario');
    }
}