<?php

/**
 * cuentaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cuentaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object cuentaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cuenta');
    }
}