<?php

/**
 * cuentapadreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cuentapadreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object cuentapadreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cuentapadre');
    }
}