<?php

/**
 * pagosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pagosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pagosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pagos');
    }
    
    public function pagoCuota($mes, $anio, $tipo, $usuario_id)
    {
      return Doctrine_Query::create()
        ->select('p.*')
        ->from('pagos p')
        ->where('MONTH(fecha) = ?', $mes)
        ->andWhere('YEAR(fecha) = ?', $anio)
        ->andWhere('tipo = ?', $tipo)
        ->andWhere('usuario_id = ?', $usuario_id)
        ->execute()->getFirst();
    }    
}