generator:
  class: sfDoctrineGenerator
  param:
    model_class:           descuentos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          descuentos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        porcentaje: { label: Descuento % }
      list:
        display: [cantidad_de_hermanos, porcentaje]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
