<div class="contenido_left">
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
                            AQUI TODO EL CODIGO HTML DE LA PLANTILLA...
</div><!--CONTENIDO LEFT-->