<?php

/**
 * Basefacturausuariofinal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $factura_usuario_id
 * @property integer $factura_final_id
 * @property facturaUsuario $facturaUsuario
 * @property facturaFinal $facturaFinal
 * 
 * @method integer             getFacturaUsuarioId()   Returns the current record's "factura_usuario_id" value
 * @method integer             getFacturaFinalId()     Returns the current record's "factura_final_id" value
 * @method facturaUsuario      getFacturaUsuario()     Returns the current record's "facturaUsuario" value
 * @method facturaFinal        getFacturaFinal()       Returns the current record's "facturaFinal" value
 * @method facturausuariofinal setFacturaUsuarioId()   Sets the current record's "factura_usuario_id" value
 * @method facturausuariofinal setFacturaFinalId()     Sets the current record's "factura_final_id" value
 * @method facturausuariofinal setFacturaUsuario()     Sets the current record's "facturaUsuario" value
 * @method facturausuariofinal setFacturaFinal()       Sets the current record's "facturaFinal" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basefacturausuariofinal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('facturausuariofinal');
        $this->hasColumn('factura_usuario_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('factura_final_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('facturaUsuario', array(
             'local' => 'factura_usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('facturaFinal', array(
             'local' => 'factura_final_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}