<?php

/**
 * mdMediaImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaImageTable extends PluginmdMediaImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaImage');
    }
}