<?php

/**
 * mdMediaIssuuVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaIssuuVideoTable extends PluginmdMediaIssuuVideoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaIssuuVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaIssuuVideo');
    }
}