<?php

/**
 * BasefacturaUsuarioDetalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $factura_id
 * @property string $description
 * @property float $amount
 * @property facturaUsuario $facturaUsuario
 * 
 * @method integer               getId()             Returns the current record's "id" value
 * @method integer               getFacturaId()      Returns the current record's "factura_id" value
 * @method string                getDescription()    Returns the current record's "description" value
 * @method float                 getAmount()         Returns the current record's "amount" value
 * @method facturaUsuario        getFacturaUsuario() Returns the current record's "facturaUsuario" value
 * @method facturaUsuarioDetalle setId()             Sets the current record's "id" value
 * @method facturaUsuarioDetalle setFacturaId()      Sets the current record's "factura_id" value
 * @method facturaUsuarioDetalle setDescription()    Sets the current record's "description" value
 * @method facturaUsuarioDetalle setAmount()         Sets the current record's "amount" value
 * @method facturaUsuarioDetalle setFacturaUsuario() Sets the current record's "facturaUsuario" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasefacturaUsuarioDetalle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('facturaUsuarioDetalle');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('factura_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('amount', 'float', 12, array(
             'type' => 'float',
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('facturaUsuario', array(
             'local' => 'factura_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}