<?php

/**
 * BasemdMediaAlbumContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $md_media_album_id
 * @property integer $md_media_content_id
 * @property string $object_class_name
 * @property integer $priority
 * @property mdMediaContent $mdMediaContent
 * @property mdMediaAlbum $mdMediaAlbum
 * 
 * @method integer             getMdMediaAlbumId()      Returns the current record's "md_media_album_id" value
 * @method integer             getMdMediaContentId()    Returns the current record's "md_media_content_id" value
 * @method string              getObjectClassName()     Returns the current record's "object_class_name" value
 * @method integer             getPriority()            Returns the current record's "priority" value
 * @method mdMediaContent      getMdMediaContent()      Returns the current record's "mdMediaContent" value
 * @method mdMediaAlbum        getMdMediaAlbum()        Returns the current record's "mdMediaAlbum" value
 * @method mdMediaAlbumContent setMdMediaAlbumId()      Sets the current record's "md_media_album_id" value
 * @method mdMediaAlbumContent setMdMediaContentId()    Sets the current record's "md_media_content_id" value
 * @method mdMediaAlbumContent setObjectClassName()     Sets the current record's "object_class_name" value
 * @method mdMediaAlbumContent setPriority()            Sets the current record's "priority" value
 * @method mdMediaAlbumContent setMdMediaContent()      Sets the current record's "mdMediaContent" value
 * @method mdMediaAlbumContent setMdMediaAlbum()        Sets the current record's "mdMediaAlbum" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdMediaAlbumContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_media_album_content');
        $this->hasColumn('md_media_album_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_media_content_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_class_name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('md_media_album_content_index', array(
             'fields' => 
             array(
              'priority' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdMediaContent', array(
             'local' => 'md_media_content_id',
             'foreign' => 'id'));

        $this->hasOne('mdMediaAlbum', array(
             'local' => 'md_media_album_id',
             'foreign' => 'id'));

        $mdcountcachebehavior0 = new mdCountCacheBehavior(array(
             'relations' => 
             array(
              'mdMediaAlbum' => 
              array(
              'columnName' => 'counter_content',
              'foreignAlias' => 'mdMediaAlbumContent',
              ),
             ),
             ));
        $this->actAs($mdcountcachebehavior0);
    }
}