<?php

/**
 * mdNewsLetterGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdNewsLetterGroupTable extends PluginmdNewsLetterGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdNewsLetterGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdNewsLetterGroup');
    }
}