<?php

/**
 * mdNewsletterContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdNewsletterContentTable extends PluginmdNewsletterContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdNewsletterContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdNewsletterContent');
    }
}