<?php

/**
 * mdMediaContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaContentTable extends PluginmdMediaContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaContent');
    }
}