<?php

/**
 * mdMediaYoutubeVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaYoutubeVideoTable extends PluginmdMediaYoutubeVideoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaYoutubeVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaYoutubeVideo');
    }
}