generator:
  class: sfDoctrineGenerator
  param:
    model_class:           usuario
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          usuario_futuros
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        actividades_list: { label: Actividades }
        referencia_bancaria: {label: Ref. Bancaria}
        anio_ingreso: {label: Año ingreso}
      list:
        fields:
          fecha_nacimiento: { date_format: dd/MM/yyyy }
        display:  [=referencia_bancaria, =apellido, nombre, fecha_nacimiento, anio_ingreso]
        sort:   [apellido, asc]
        max_per_page: 30
        table_method: addFuturosFilter
        actions: []
      filter:
        display:  [referencia_bancaria, apellido, nombre, futuro_colegio, anio_ingreso]
      form:    ~
      edit:    ~
      new:     ~
