<?php

/**
 * PluginmdNewsLetterGroupUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsLetterGroupUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsLetterGroupUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsLetterGroupUser');
    }
    
    public function retrieveByGroupAndUserId($groupId, $userId)
    {
      $query = $this->createQuery("mdNLGU")
           ->addWhere("mdNLGU.md_newsletter_group_id = ?", $groupId)
           ->addWhere("mdNLGU.md_newsletter_user_id = ?", $userId);
      return $query->fetchOne();
    }
}
