<?php

/**
 * BasemdI18NManageClasses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $class_name
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getClassName()  Returns the current record's "class_name" value
 * @method mdI18NManageClasses setId()         Sets the current record's "id" value
 * @method mdI18NManageClasses setClassName()  Sets the current record's "class_name" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdI18NManageClasses extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_i18_n_manage_classes');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('class_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}