<?php

/**
 * PluginmdNewsletterContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterContent');
    }
    
    public function retrieveAdminQuery()
    {
      return $this->createQuery("mdLC")->orderBy("created_at desc");
    }
}
