<?php

/**
 * mdBlockedUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdBlockedUsersTable extends PluginmdBlockedUsersTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdBlockedUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdBlockedUsers');
    }
}