<?php

/**
 * mdContentRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdContentRelationTable extends PluginmdContentRelationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdContentRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdContentRelation');
    }
}