<?php

/**
 * mdUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdUserTable extends PluginmdUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdUser');
    }
}