<?php

/**
 * mdMediaAlbumContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaAlbumContentTable extends PluginmdMediaAlbumContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaAlbumContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaAlbumContent');
    }
}