<?php

/**
 * mdMediaFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaFileTable extends PluginmdMediaFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaFile');
    }
}