<?php

/**
 * Basecostos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property float $matricula
 * @property float $matutino
 * @property float $vespertino
 * @property float $doble_horario
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method float   getMatricula()     Returns the current record's "matricula" value
 * @method float   getMatutino()      Returns the current record's "matutino" value
 * @method float   getVespertino()    Returns the current record's "vespertino" value
 * @method float   getDobleHorario()  Returns the current record's "doble_horario" value
 * @method costos  setId()            Sets the current record's "id" value
 * @method costos  setMatricula()     Sets the current record's "matricula" value
 * @method costos  setMatutino()      Sets the current record's "matutino" value
 * @method costos  setVespertino()    Sets the current record's "vespertino" value
 * @method costos  setDobleHorario()  Sets the current record's "doble_horario" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecostos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('costos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('matricula', 'float', 6, array(
             'type' => 'float',
             'notnull' => true,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('matutino', 'float', 6, array(
             'type' => 'float',
             'notnull' => true,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('vespertino', 'float', 6, array(
             'type' => 'float',
             'notnull' => true,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('doble_horario', 'float', 6, array(
             'type' => 'float',
             'notnull' => true,
             'length' => 6,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}