<?php

/**
 * mdPassportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdPassportTable extends PluginmdPassportTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdPassportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdPassport');
    }
}