<?php

/**
 * mdUserSearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdUserSearchTable extends PluginmdUserSearchTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdUserSearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdUserSearch');
    }
}