<?php

/**
 * mdMediaVimeoVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaVimeoVideoTable extends PluginmdMediaVimeoVideoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaVimeoVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaVimeoVideo');
    }
}