<?php

/**
 * mdMediaVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaVideoTable extends PluginmdMediaVideoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaVideo');
    }
}