generator:
  class: sfDoctrineGenerator
  param:
    model_class:           progenitor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          progenitor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, nombre, direccion, telefono, mail]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
