<?php

/**
 * PluginmdNewsletterContentSendedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterContentSendedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterContentSendedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterContentSended');
    }
    
    public function retrieveNotSended()
    {
      $time = date('Y-m-d H:i:s',time());
      
      $record = $this->createQuery('a')->select('TIMEDIFF("' . $time . '", NOW()) as time')->limit(1)->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);

      $diff = $record['time'];
      
      $query = $this->createQuery("mdNLCS")
            ->addWhere("mdNLCS.sended = ?", false)
            ->addWhere("mdNLCS.sending_date <= ?", 'ADDTIME("' . date('Y-m-d H:i:s',time()) . '", "' . $diff . '")');

      return $query->execute();
    }    
    
    /*public function retrieveNotSended()
    {
      $query = $this->createQuery("mdNLCS")
            ->addWhere("mdNLCS.sended = ?", false)
            ->addWhere("mdNLCS.sending_date <= ?", date('Y-m-d H:i:s',time()));
      return $query->execute();
    }*/
    
    public function retrieveAllMdNewsletterContentSendedOfId($id)
    {
      $query = $this->createQuery("mdNLCS")
            ->addWhere("mdNLCS.md_newsletter_content_id = ?", $id)
            ->orderBy("mdNLCS.created_at DESC");
      return $query->execute();
    }
        
}
