<?php

/**
 * PluginmdNewsLetterGroupSendedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsLetterGroupSendedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsLetterGroupSendedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsLetterGroupSended');
    }
    
    public function retrieveByGroupAndSended($groupId, $sendedId)
    {
      $query = $this->createQuery("mdLGS")
            ->addWhere("mdLGS.md_newsletter_group_id = ?", $groupId)
            ->addWhere("mdLGS.md_newsletter_contend_sended_id = ?", $sendedId);
      return $query->fetchOne();
    }
}
