<?php

/**
 * PluginmdBlockedUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdBlockedUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdBlockedUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdBlockedUsers');
    }
}