<?php

/**
 * mdNewsletterSendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdNewsletterSendTable extends PluginmdNewsletterSendTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdNewsletterSendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdNewsletterSend');
    }
}