<?php

/**
 * mdI18NManageClassesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdI18NManageClassesTable extends PluginmdI18NManageClassesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdI18NManageClassesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdI18NManageClasses');
    }
}