<?php

/**
 * PluginmdMediaVimeoVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdMediaVimeoVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdMediaVimeoVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdMediaVimeoVideo');
    }
    
    public function retrieveObject($object_id, $timeToLife = 86400, $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
        //Creamos la Doctrine Query
        $query = $this->createQuery("mdMVV")
                    ->where('mdMVV.id = ?', $object_id);

        //Seteamos modo de hidratacion
        $query = $query->setHydrationMode($hydrationMode);

        //Cacheamos el resultado
        if(sfConfig::get('sf_driver_cache') && Md_Cache::$_use_cache)
        {
            $query->useResultCache(true, $timeToLife, sfConfig::get('sf_root_dir') . '_' . $this->getTableName() . '_' . $object_id . '_' . $hydrationMode);
        }

        return $query->fetchOne();
    }    
}