<?php

/**
 * mdPassportRememberKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdPassportRememberKeyTable extends PluginmdPassportRememberKeyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdPassportRememberKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdPassportRememberKey');
    }
}