<?php

/**
 * mdUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jardin
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mdUser extends PluginmdUser
{
  public function postSave($event){
    parent::postSave($event);
    
    $mdNewsletterUser = Doctrine::getTable('mdNewsLetterUser')->findOneByMdUserId($this->getId());
    if(!$mdNewsletterUser){
      $mdNewsletterUser = new mdNewsLetterUser();
      $mdNewsletterUser->setMdUserId($this->getId());
      $mdNewsletterUser->save();
    }
  }
}
