generator:
  class: sfDoctrineGenerator
  param:
    model_class:           actividades
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          actividades
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:  [=nombre, costo, horario]
      filter:
        display:  [nombre, costo, horario]
      form:    ~
      edit:    ~
      new:     ~
