<?php

/**
 * mdNewsLetterUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdNewsLetterUserTable extends PluginmdNewsLetterUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdNewsLetterUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdNewsLetterUser');
    }
}