<?php

/**
 * PluginmdNewsletterSendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterSendTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginmdNewsletterSendTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginmdNewsletterSend');
  }

  public function scheduledSend($limit) {
    $time = date('Y-m-d H:i:s', time());

    $record = $this->createQuery('a')->select('TIMEDIFF("' . $time . '", NOW()) as time')->limit(1)->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);

    $diff = $record['time'];

    $query = Doctrine::getTable('mdNewsletterSend')
            ->createQuery('ns')
            ->leftJoin('ns.mdNewsletterContentSended as ncs')
            ->where('ns.sending_date IS NULL')
            ->andWhere("ncs.sending_date <= ?", 'ADDTIME("' . date('Y-m-d H:i:s', time()) . '", "' . $diff . '")')
            ->andWhere("ncs.sended = ?", false)
            ->limit($limit);

    return $query->execute();
  }

}