<?php

/**
 * BasemdPassportRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $md_passport_id
 * @property string $remember_key
 * @property string $ip_address
 * @property mdPassport $mdPassport
 * 
 * @method integer               getId()             Returns the current record's "id" value
 * @method integer               getMdPassportId()   Returns the current record's "md_passport_id" value
 * @method string                getRememberKey()    Returns the current record's "remember_key" value
 * @method string                getIpAddress()      Returns the current record's "ip_address" value
 * @method mdPassport            getMdPassport()     Returns the current record's "mdPassport" value
 * @method mdPassportRememberKey setId()             Sets the current record's "id" value
 * @method mdPassportRememberKey setMdPassportId()   Sets the current record's "md_passport_id" value
 * @method mdPassportRememberKey setRememberKey()    Sets the current record's "remember_key" value
 * @method mdPassportRememberKey setIpAddress()      Sets the current record's "ip_address" value
 * @method mdPassportRememberKey setMdPassport()     Sets the current record's "mdPassport" value
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdPassportRememberKey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_passport_remember_key');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_passport_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('remember_key', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('ip_address', 'string', 50, array(
             'type' => 'string',
             'primary' => true,
             'length' => 50,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdPassport', array(
             'local' => 'md_passport_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}