<?php

/**
 * PluginmdMediaFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginmdMediaFile extends BasemdMediaFile implements mdMediaContentInterface
{

    public $priority = -1;

    public $mdUserIdTmp = 0;

    public $mdNameSpaceIdTmp = 0;

    /**
     * Devuelve el nombre de la clase: mdMediaFile
     * @return <string>
     */
    public function getObjectClass()
    {
        return get_class($this);
    }

    /**
     * Devuelve el src de la imagen, segun la extension del archivo
     * @return <string>
     */
    public function getObjectSource()
    {
        if($this->getFiletype() == 'pdf'){
            return '/../mdMediaDoctrinePlugin/images/adobe_acrobat_pdf_icon.jpg';
        }
        if($this->getFiletype() == 'doc' || $this->getFiletype() == 'docx'){
            return '/../mdMediaDoctrinePlugin/images/office_word_icon.png';
        }
        if($this->getFiletype() == 'xls' || $this->getFiletype() == 'xlsx'){
            return '/../mdMediaDoctrinePlugin/images/office_excel_icon.png';
        }
        if($this->getFiletype() == 'ppt' || $this->getFiletype() == 'pptx'){
            return '/../mdMediaDoctrinePlugin/images/office_powerpoint_icon.png';
        }
        return $this->getPath() . $this->getFilename();
    }

    public function getDownloadSource()
    {
        return $this->getPath() . $this->getFilename();
    }
    
    public function getObjectUrl($options = array())
    {
        return mdWebImage::getUrl($this->getObjectSource(), $options);
    }

    public function preDelete($event) {
        $path = sfConfig::get('app_mdImageFileHandler_path', sfConfig::get('sf_upload_dir'));
        $path .= $this->getPath();
        try{
            MdFileHandler::delete($this->getFilename(), $path);
        }catch(Exception $e)
        {
            sfContext::getInstance()->getLogger()->err("Error al borrar: ".$path.$this->getFilename());
            sfContext::getInstance()->getLogger()->err($e->getMessage());
        }
    }
  
    public function isVideo()
    {
      return false;
    }
}
