<?php

/**
 * cuenta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jardin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class cuenta extends Basecuenta
{
  public function preSave($event) {
    $this->setDiferencia($this->getDebe() - $this->getPago());
    parent::preSave($event);
  }
  
  public function getFormatedDiferencia()
  {
    return number_format($this->getDiferencia(), 0, ',', '.');
  }

}
