<?php

/**
 * emailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class emailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object emailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emails');
    }
}