<?php

/**
 * facturaFinalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class facturaFinalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object facturaFinalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('facturaFinal');
    }
    
    public function retrieveByAccountMonthAndYear($accountId, $month, $year)
    {
        $query = $this->createQuery('f')
                ->addWhere('f.cuenta_id = ?', $accountId)
                ->addWhere('f.month = ?', $month)
                ->addWhere('f.year = ?', $year);
        return $query->fetchOne();
    }
}