<?php

/**
 * mdGaleria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ulapsi
 * @subpackage model
 * @author     Gaston Caldeiro
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mdGaleria extends BasemdGaleria
{
  public function getObjectClass() {
    return get_class();
  }

  public function getSlug() {
    return mdBasicFunction::slugify($this->getTitulo());
  }

}
