<?php

/**
 * usuario_actividadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class usuario_actividadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object usuario_actividadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('usuario_actividades');
    }
}