<?php

/**
 * mdUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdUserProfileTable extends PluginmdUserProfileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdUserProfile');
    }
}