<?php

/**
 * PluginmdMediaVimeoVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdMediaVimeoVideo extends BasemdMediaVimeoVideo implements mdMediaContentInterface
{
  public $priority = -1;
  
  public $mdUserIdTmp = 0;
  
  public function getObjectClass()
  {
    return get_class($this);
  }
  
  public function preSave($event) 
  {
    parent::preSave($event);
    if($this->isNew())
    {
      $mdVimeo = new mdVimeo();
      $mdVimeo->setUrl($this->getVimeoUrl());
      
      // Guardo todos los datos del video
      $object = $mdVimeo->getEmbedObject();      

      $this->setTitle($object->title);
      $this->setAuthorName($object->author_name);
      $this->setAuthorUrl($object->author_url);
      $this->setAvatar($object->thumbnail_url);
      $this->setAvatarWidth($object->thumbnail_width);
      $this->setAvatarHeight($object->thumbnail_height);
      $this->setDescription($object->description);
      $this->setDuration($object->duration);
      $this->setSrc($mdVimeo->getSrc($object));
    }
  }
  
  public function getObjectUrl($options = array())
  {
    return $this->getAvatar();
  }
  
  public function retrieveEmbeddedCode($options = array())
  {
    $width = 480;
    $height = 390;
    
    if(isset($options['width'])) $width = $options['width'];
    if(isset($options['height'])) $height = $options['height'];
    
    return '<iframe title="' . $this->getTitle() . '" src="' . $this->getSrc() . '" width="' . $width . '" height="' . $height . '" frameborder="0" allowfullscreen></iframe>';
  }

  public function getObjectSource()
  {
    return "";
  }
  
  public function isVideo()
  {
    return true;
  }  
}
