<?php

/**
 * mdNewsLetterGroupSendedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdNewsLetterGroupSendedTable extends PluginmdNewsLetterGroupSendedTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdNewsLetterGroupSendedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdNewsLetterGroupSended');
    }
}