<?php

/**
 * mdNewsletterContentSendedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdNewsletterContentSendedTable extends PluginmdNewsletterContentSendedTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdNewsletterContentSendedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdNewsletterContentSended');
    }
}