<?php

/**
 * mdNewsLetterGroupUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdNewsLetterGroupUserTable extends PluginmdNewsLetterGroupUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdNewsLetterGroupUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdNewsLetterGroupUser');
    }
}