<?php

/**
 * mdMediaAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdMediaAlbumTable extends PluginmdMediaAlbumTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdMediaAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdMediaAlbum');
    }
}